// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGxfunmX6nLF8OO0MflBQ99LQ4eK2ohBg',
    appId: '1:316006552837:web:283684c1fd6fdb6045936c',
    messagingSenderId: '316006552837',
    projectId: 'chat-app-8f1f4',
    authDomain: 'chat-app-8f1f4.firebaseapp.com',
    storageBucket: 'chat-app-8f1f4.appspot.com',
    measurementId: 'G-EGH2HX8Q46',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP-S9tpNBgYF82lqJtpJp5780XbNBgKKM',
    appId: '1:316006552837:android:de679613b3838ffc45936c',
    messagingSenderId: '316006552837',
    projectId: 'chat-app-8f1f4',
    storageBucket: 'chat-app-8f1f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr9i5LYebrPYENw2o-6WbWrV5z6L8JGjs',
    appId: '1:316006552837:ios:cbe449d36afc7e4645936c',
    messagingSenderId: '316006552837',
    projectId: 'chat-app-8f1f4',
    storageBucket: 'chat-app-8f1f4.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAr9i5LYebrPYENw2o-6WbWrV5z6L8JGjs',
    appId: '1:316006552837:ios:cbe449d36afc7e4645936c',
    messagingSenderId: '316006552837',
    projectId: 'chat-app-8f1f4',
    storageBucket: 'chat-app-8f1f4.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGxfunmX6nLF8OO0MflBQ99LQ4eK2ohBg',
    appId: '1:316006552837:web:4efa33d66f6c4e2145936c',
    messagingSenderId: '316006552837',
    projectId: 'chat-app-8f1f4',
    authDomain: 'chat-app-8f1f4.firebaseapp.com',
    storageBucket: 'chat-app-8f1f4.appspot.com',
    measurementId: 'G-7MJTW2TSX5',
  );
}
